### ISSUE TITLE
Multiple refunds in woocommerce

### ISSUE THREAD

**Issue by noaholsson** [SwedbankPay/swedbank-pay-woocommerce-payments#129]
### Problem: 
When refunding an order from Woocommerce admin when paid with Swish, two refunds appear in Woocoomerce admin which results in the paid amount being wrong. The actual refund is sent to Swedbank Pay is correct and paid to the customer correctly, but this affects the statistics and the order list. 

### Cause: 
From what I can tell it seems to have something with the callback to do, everything is correct until it's executed creating an extra refund order. What I can find is that the `_transaction_id` metadata is never set on the refund created by Woocommerce which results in the core package creating another one. 

### Versions:
WordPress: 5.8.4
Woocommerce: 5.9.1
Swedbank Pay Payments: 4.4.2

**Comment by olegisk** [comment]
@noaholsson To troubleshoot this we need access to your site. You can send details to [info@aait.se](mailto:info@aait.se)

**Comment by noaholsson** [comment]
@olegisk I have sent over access information to a demo site now.
