### ISSUE TITLE
Kan ej lägga order - Input validation failed, error description in problems node!

### ISSUE THREAD

**Issue by seodrweb** [SwedbankPay/swedbank-pay-woocommerce-payments#145]
Vi har problem med att det inte går att lägga beställning med Swedbank Pay. När man matat in sina uppgifter i Swedbank Pay och går vidare och klickar "Lägg beställning" så dyker detta felmeddelande upp:

**"Input validation failed, error description in problems node!
PaymentOrder.Payer.ConsumerProfileRef: Both ConsumerProfileRef and PayerReference cannot be set at the same time."**

Se skärmdump: https://i.postimg.cc/TRs2Yv44/Ska-rmavbild-2023-03-15-kl-13-04-07.png

PHP-version: 8.028
Wordpress: 6.1.1
Swedbank Pay 7.0
WooCoommerce: 7.4.1

**Comment by olegisk** [comment]
This issue is not related to Payments module. It's for Checkout https://github.com/SwedbankPay/swedbank-pay-woocommerce-checkout
