### ISSUE TITLE
Is the php-name-parser lib used?

### ISSUE THREAD

**Issue by lakrisgubben** [SwedbankPay/swedbank-pay-woocommerce-payments#15]
Hi,

the php-name-parser lib is spitting out loads of `Array and string offset access syntax with curly braces is deprecated` notices when running on php 7.4. I was first thinking of opening a PR on the aait/php-name-parser repo. But when searching through this codebase the only reference to the class `FullNameParser` I could find [was when it was included.](https://github.com/SwedbankPay/swedbank-pay-woocommerce-payments/blob/master/swedbank-pay-woocommerce-payments.php#L105) So my question is: is this lib used in this plugin? If not could it be dropped to stop all these deprecation notices? If it is used I'm happy to make a PR to fix these notices.

**Comment by aait** [comment]
@mikaelengstrom Yes, fullnameparser wasn't updated long time ago, so it have problems with php 7.4. I have replaced this library to adci/full-name-parser

**Comment by mikaelengstrom** [comment]
Guess you ment to tag @lakrisgubben and bot me ;)

**Comment by lakrisgubben** [comment]
thanks @aait! :)

Any timeline for when this plugin will be considered "stable"? (Since the old payex api for card payments is closing down soon).

**Comment by asbjornu** [comment]
@lakrisgubben, the stability of the code itself is pretty good, but as we are experiencing edge cases that aren't taken care of yet (especially in relation to other installed plugins), we don't have full support of our APIs yet (recurring payments / subscriptions being one important missing feature, for instance) and last, but most importantly; we aren't in a position to offer full support of the plugins as of yet, we declare them "unsupported" for now.

You are free to use our SDKs and plugins in production, but unfortunately can't expect much more support from us than you can from any other open source library. That will change in due time, though. Thanks for your patience!

**Comment by lakrisgubben** [comment]
@asbjornu thanks for the detailed response! Glad to hear that. :) Would y'all consider master to be the stable branch to install the plugin (via composer) from, or would you recommend getting it from wp.org (as in will there be continous releases to wp.org if one finds bugs and report/fix them here)?

**Comment by asbjornu** [comment]
@lakrisgubben, GitHub `master` will always be fresher than [wordpress.org](https://wordpress.org/plugins/swedbank-pay-payments/), but we try to keep the latter up to date contiunally. The recommended way to install is via wp.org so updates are visible and easier to install (for most people).

**Comment by lakrisgubben** [comment]
thanks @asbjornu
