### ISSUE TITLE
Should the installer set the current db version?

### ISSUE THREAD

**Issue by lakrisgubben** [SwedbankPay/swedbank-pay-woocommerce-payments#16]
When the [install script runs it sets the db version to 1.1.0](https://github.com/SwedbankPay/swedbank-pay-woocommerce-payments/blob/master/includes/class-wc-swedbank-plugin.php#L115), but the current db version is 1.2.0. I think either the 1.2.0 upgrade process should run during install or the version should be set to 1.2.0 in the installer. When looking at the 1.2.0 upgrader it seems that it shouldn't need to run on a fresh install?

**Comment by aait** [comment]
@lakrisgubben If your database doesn't have woocommerce_payex_psp_version flag then means scheme version 1.1.0 and needs install some data during an upgrade

**Comment by lakrisgubben** [comment]
@aait yep, I get it. I just thought that this should be a part of the "install" process. Feels weird that it does an install and then directly asks the user to upgrade the db. And since it seems that the 1.2.0 upgrade only adds older orders to the queue this should not be needed on a fresh install and therefore the installer could set the db version to 1.2.0 instead of 1.1.0. But I might of course be missing something, not that familiar with the code yet. ;)

And actually, the check for `woocommerce_payex_psp_version` uses a fallback to 1.2.0 in get_option so if that option does not exist I don't think any upgrades will be run.
