### ISSUE TITLE
Consider using a different capability than update_plugins in the db upgrader

### ISSUE THREAD

**Issue by lakrisgubben** [SwedbankPay/swedbank-pay-woocommerce-payments#17]
If one uses composer to install wp and plugins one has usually restricted so that plugins can't be updated/added via the gui, this means that no user has the `update_plugins` capability and the upgrade db notice is never shown (it uses the check for `update_plugins` on [two](https://github.com/SwedbankPay/swedbank-pay-woocommerce-payments/blob/master/includes/class-wc-swedbank-plugin.php#L490) [occurences](https://github.com/SwedbankPay/swedbank-pay-woocommerce-payments/blob/master/includes/class-wc-swedbank-plugin.php#L505)).

Here's a [list with other capabilities that are only assigned to super admins in a multisite and regular admins in a single site](https://wordpress.org/support/article/roles-and-capabilities/#additional-admin-capabilities), maybe one of them that does not check for filesystem access could be used?

**Comment by aait** [comment]
@lakrisgubben What capability can you suggest then? May be ```manage_woocommerce```?

**Comment by lakrisgubben** [comment]
@aait `manage_woocommerce` sounds like a smart one. :) Otherwise something like `delete_users` or `unfiltered_html` will only be true for super admins on a multisite or regular admins on a single site

**Comment by lakrisgubben** [comment]
@aait thanks for the quick fixes! ❤️ Have a nice weekend!
