### ISSUE TITLE
Improved error message for incorrect or non existing credentials

### ISSUE THREAD

**Issue by aait** [SwedbankPay/swedbank-pay-woocommerce-payments#21]
At the moment the plugin does not give an explanatory error message.
Error message should be:
`PAYEE_ID is missing`
`MERCHANT_TOKEN` is missing
or
API credentials invalid, please update in settings.

**Comment by asbjornu** [comment]
@aait, as this probably affects both Payments and Checkout, this is something that can and should be done in the [Core plugin](https://github.com/SwedbankPay/swedbank-pay-woocommerce-core), no?

**Comment by aait** [comment]
can I move the issue to the core-plugin in an easy way?

**Comment by asbjornu** [comment]
I created WOO-24 for it in Jira, so you can track it there instead. Then this bug can be closed with `Fixes #21` in the PR that updates the Core library here.

**Comment by aait** [comment]
This issue has been solved over [there](https://github.com/SwedbankPay/swedbank-pay-woocommerce-payments/commit/8209ad7ac5ea21cb5691a8b906dcecca60783798)
