### ISSUE TITLE
Missing payex_transaction table

### ISSUE THREAD

**Issue by noaholsson** [SwedbankPay/swedbank-pay-woocommerce-payments#36]
**Problem**
Some database providers don't allow indexing on large columns. This caused the `payex_transactions` to not get created. Which led to orders getting stuck on "Awaiting payment". 

**Possible solution**
You should add some form of validation that the table actually gets created since this causes quite a lot of problems. I would propose that you also verify that the transactions really gets inserted.

**Comment by asbjornu** [comment]
Thanks for the report, @noaholsson. We'll investigate and provide a fix if possible.

**Comment by aait** [comment]
@noaholsson Which field was large?
Plugin creates table with follow fields and sizes:

>   `transaction_id` int(11) NOT NULL AUTO_INCREMENT,
  `transaction_data` text,
  `order_id` int(11) DEFAULT NULL,
  `id` varchar(255) DEFAULT NULL,
  `created` datetime DEFAULT NULL,
  `updated` datetime DEFAULT NULL,
  `type` varchar(128) DEFAULT NULL,
  `state` varchar(128) DEFAULT NULL,
  `number` varchar(128) DEFAULT NULL,
  `amount` bigint(20) DEFAULT NULL,
  `vatAmount` bigint(20) DEFAULT NULL,
  `description` varchar(255) DEFAULT NULL,
  `payeeReference` varchar(255) DEFAULT NULL,
>

Plugins creates follow indexes:
> PRIMARY KEY (`transaction_id`),
  UNIQUE KEY `number` (`number`),
  KEY `id` (`id`),
  KEY `order_id` (`order_id`)

**Comment by noaholsson** [comment]
The id column was the one that was to large to index.

**Comment by aait** [comment]
@noaholsson ok, which length of this value would be ok for you?

**Comment by noaholsson** [comment]
The way I solved it was by removing the index of this column. I figured since you almost never fetched the transactions by id, this wouldn't affect the performance noticeble.
