### ISSUE TITLE
Error "API Exception. Please check the logs."

### ISSUE THREAD

**Issue by rowhit07** [SwedbankPay/swedbank-pay-woocommerce-payments#40]
While checking out I get an error saying 'API Exception. Please check the logs.'
But when I enable test mode and order product, it is redirected to the respective payment page.
Previously also I used to get this error. But with the plugin update, it was working fine.
But now again I am getting the issue.

**Comment by asbjornu** [comment]
Thanks for the bug report. We'll investigate and provide a fix if we can identify this as a bug in the plugin.

**Comment by rowhit07** [comment]
Hi @asbjornu 
Any solution to this? The issue is in the live site and it's affecting a lot right now. 
Our users are not being able to make payments.

**Comment by rowhit07** [comment]
Hi,

Did you find any solution to that issue?
The site is https://exerto.no/
If you buy any membership https://exerto.no/butikk/ you then go to the
checkout page.
But it's giving the error.
But when in testing mode it works. I can't figure it out how to resolve

Rohit Bajracharya
Senior WordPress Developer | CodePixelz Media <https://codepixelzmedia.com/>
M: 9849837544
E: row.hit.07@gmail.com
A: Nepal
[image: facebook] <https://www.facebook.com/rohitbaj> [image: linkedin]
<https://www.linkedin.com/in/rohit-bajracharya/> [image: github]
<https://github.com/rowhit07>

**Comment by aait** [comment]
Hi @rowhit07, would be good if you could provide the logs at woo-> status -> logs; the one related to SwedbankPay (or payex) for the relevant date. Or give us access (mail to info@aait.se) . My first hunch is that it is something related to account setup or credentials, please contact support.ecom@payex.com to confirm that your account is setup the right way and that you use the correct credentials
