### ISSUE TITLE
php 7.4 deprecation warnings

### ISSUE THREAD

**Issue by mikaelengstrom** [SwedbankPay/swedbank-pay-woocommerce-payments#43]
This plugin throws a few deprecation warnings on php 7.4: 

Deprecated: Array and string offset access syntax with curly braces is deprecated in /app/src/app/plugins/woocommerce-payments/vendors/php-name-parser/vendor/aait/php-name-parser/parser.php on line 437
Deprecated: Array and string offset access syntax with curly braces is deprecated in /app/src/app/plugins/woocommerce-payments/vendors/php-name-parser/vendor/aait/php-name-parser/parser.php on line 477
Deprecated: Array and string offset access syntax with curly braces is deprecated in /app/src/app/plugins/woocommerce-payments/vendors/php-name-parser/vendor/aait/php-name-parser/parser.php on line 477
Deprecated: Array and string offset access syntax with curly braces is deprecated in /app/src/app/plugins/woocommerce-payments/vendors/php-name-parser/vendor/aait/php-name-parser/parser.php on line 481
Deprecated: Array and string offset access syntax with curly braces is deprecated in /app/src/app/plugins/woocommerce-payments/vendors/php-name-parser/vendor/aait/php-name-parser/parser.php on line 481
Deprecated: Array and string offset access syntax with curly braces is deprecated in /app/src/app/plugins/woocommerce-payments/vendors/php-name-parser/vendor/aait/php-name-parser/parser.php on line 485
Deprecated: Array and string offset access syntax with curly braces is deprecated in /app/src/app/plugins/woocommerce-payments/vendors/php-name-parser/vendor/aait/php-name-parser/parser.php on line 485
Deprecated: Array and string offset access syntax with curly braces is deprecated in /app/src/app/plugins/woocommerce-payments/vendors/php-name-parser/vendor/aait/php-name-parser/parser.php on line 489
Deprecated: Array and string offset access syntax with curly braces is deprecated in /app/src/app/plugins/woocommerce-payments/vendors/php-name-parser/vendor/aait/php-name-parser/parser.php on line 489
Deprecated: Array and string offset access syntax with curly braces is deprecated in /app/src/app/plugins/woocommerce-payments/vendors/php-name-parser/vendor/aait/php-name-parser/parser.php on line 489

**Comment by aait** [comment]
@mikaelengstrom Please update the plugin to latest version

**Comment by mikaelengstrom** [comment]
I am using the latest stable version available on packagist under "swedbank-pay/woocommerce-payments": v1.3.1. Would you consider the beta production ready?

**Comment by aait** [comment]
@mikaelengstrom We will fix it

**Comment by aait** [comment]
@mikaelengstrom The latest version of plugin doesn' use `php-name-parser` library. It uses `adci/full-name-parser` instead of
