### ISSUE TITLE
 Fatal error when activated

### ISSUE THREAD

**Issue by asbjornu** [SwedbankPay/swedbank-pay-woocommerce-payments#45]
@wickywills [writes](https://wordpress.org/support/topic/fatal-error-when-activated-8/):

>When activated on a brand new installation with just WooCommerce installed, I receive the following:
>```
>Fatal error: Uncaught SwedbankPay\Api\Client\Exception: VERSION not found in constant variable SwedbankPay\Api\Client\VERSION, composer.json, composer.lock or anywhere else. in /kunder/site/public/wp-content/plugins/swedbank-pay-payments/vendor/swedbank-pay/swedbank-pay-sdk-php/src/SwedbankPay/Api/Client/ClientVersion.php:99 Stack trace: #0 /kunder/site/public/wp-content/plugins/swedbank-pay-payments/vendor/swedbank-pay/swedbank-pay-sdk-php/src/SwedbankPay/Api/Client/ClientVersion.php(22): SwedbankPay\Api\Client\ClientVersion->getVersionFromEnvironment() #1 /kunder/site/public/wp-content/plugins/swedbank-pay-payments/vendor/swedbank-pay/swedbank-pay-sdk-php/src/SwedbankPay/Api/Client/Client.php(65): SwedbankPay\Api\Client\ClientVersion->__construct() #2 /kunder/site/public/wp-content/plugins/swedbank-pay-payments/vendor/swedbank-pay/swedbank-pay-woocommerce-core/src/SwedbankPay/Core/Core.php(97): SwedbankPay\Api\Client\Client->__construct() #3 /ku in /kunder/site/public/wp-content/plugins/swedbank-pay-payments/vendor/swedbank-pay/swedbank-pay-sdk-php/src/SwedbankPay/Api/Client/ClientVersion.php on line 99
>```

**Comment by aait** [comment]
@asbjornu Fixed

**Comment by asbjornu** [comment]
@aait, can you please reference the commit or pull request in which it was fixed?

**Comment by aait** [comment]
@aait Problem was composer.json issue in the sdk. There was missing version parameter. I've fixed it in generated packages on wordpress SVN.
