### ISSUE TITLE
Logger does not respect the "Enable logging" setting

### ISSUE THREAD

**Issue by lakrisgubben** [SwedbankPay/swedbank-pay-woocommerce-payments#46]
The `log` method on the `WC_Background_Swedbank_Pay_Queue` class does not respect the "Enable logging" setting for the current payment gateway. See https://github.com/SwedbankPay/swedbank-pay-woocommerce-core/issues/16 for a similar issue.

As far as I can tell the `WC_Background_Swedbank_Pay_Queue` does not have access to the current payment gateway class, so I'm not sure what the best way to check for the "Enable logging" setting is. But I'm not super famililar with the code either, so y'all probably have a good idea for how to do that. :)

**Comment by lakrisgubben** [comment]
Maybe the best is to use the log setting from the CC payment option if that is active, and then fall back to another active payment gateway. I don't know. But it would be nice if WC_Background_Swedbank_Pay_Queue didn't write to the log if one has not enabled logging on any payment gateway. ping @aait @asbjornu :)

**Comment by lakrisgubben** [comment]
@aait @asbjornu thanks for fixing the logging issues in https://github.com/SwedbankPay/swedbank-pay-woocommerce-core/issues/16 The only thing still left where logging is happening regardless of once's settings is the logging done by the background queue. Would be awesome to get that fixed as well. :)

**Comment by aait** [comment]
@lakrisgubben Thanks. Actually, i don't want to get rid of the background queue because those logs can be very helpful if something wrong. Those logs can be very helpful.

**Comment by lakrisgubben** [comment]
@aait fair enough. :)
