### ISSUE TITLE
Inifnite loop when order get status failed

### ISSUE THREAD

**Issue by Exanity** [SwedbankPay/swedbank-pay-woocommerce-payments#47]
There seems to be and inifinite loop when you get redirected back from swedbank pay with the status "failed"

To recreate this problem you can use these card deatails "4761739001010416 12/22 268" and when you get to the page you choose "failed" in the dropdown 4 times in a row.

An exampel on a fix that seems to work for me is: 
```
elseif ($status == 'failed'){
  break;
}
```
in public function thankyou_page at line 665 in the file swedbank-pay-payments/includes/class-wc-gateway-swedbank-pay-cc.php

**Comment by asbjornu** [comment]
Thanks for the report, @Exanity. We will get to work on that ASAP. We do accept pull requests too, if you want to submit one.

**Comment by aait** [comment]
@Exanity @asbjornu I'm not sure that that's a good solution
