### ISSUE TITLE
Not possible to install latest plugin using composer without adding a minimum-stability setting

### ISSUE THREAD

**Issue by marteinn** [SwedbankPay/swedbank-pay-woocommerce-payments#60]
Currently when you try to install the latest version of this plugin (as of this date 3.2.0) using composer you'll get an minimum-stability conflict.

Using: `"swedbank-pay/woocommerce-payments": "3.2.0"`

```
Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - Installation request for swedbank-pay/woocommerce-payments 3.2.0@dev -> satisfiable by swedbank-pay/woocommerce-payments[v3.2.0].
    - swedbank-pay/woocommerce-payments v3.2.0 requires swedbank-pay/swedbank-pay-woocommerce-core dev-master -> satisfiable by swedbank-pay/swedbank-pay-woocommerce-core[dev-master] but these conflict with your requirements or minimum-stability.
```

I also tried adding `@dev` at the end (`3.2.0@dev`) but still got the same result.

The only way for me, right now to install the plugin is to add this in my composer root file.

```
"prefer-stable": true,
"minimum-stability": "dev"
```

I know this plugin is in beta, but I think its a good idea to allow users to install plugin without defining a global setting that might effect the user project. If not possible, perhaps pin `swedbank-pay-woocommerce-core` to a stable package?

Thanks!

**Comment by aait** [comment]
@asbjornu We will sovle this problem when sdk v4 will be ready

**Comment by lakrisgubben** [comment]
bumping this now that sdk is at v4 and wc-core is at v3. Would be great to be able to use only stable packages! :)
