### ISSUE TITLE
Plugin causes timeouts on environments which has 30/60 second max execution time

### ISSUE THREAD

**Issue by marteinn** [SwedbankPay/swedbank-pay-woocommerce-payments#70]
This plugin seems to assume that it is run in a environment with a high maximum execution timeout, which causes certain errors (such as server overload/gateway timeout) when run on environments which has a max execution time set to 30 or 60 seconds.

This is one example that I found (where a max wait of 60 seconds are assumed + additional request latency time)
https://github.com/SwedbankPay/swedbank-pay-woocommerce-payments/blob/1b29c725b00420850d86cc46953d8d7fb4ba3ce9/includes/class-wc-gateway-swedbank-pay-cc.php#L653

Is this type of error expected to cause a server overload/gateway timeout? If not my suggestion is either to adjust max wait time according to environment, lower max wait time to fit within 30 seconds (which is php ini default) or find another architecture for this type of problem.

**Comment by aait** [comment]
This issue could be solved with that pull request https://github.com/SwedbankPay/swedbank-pay-woocommerce-payments/pull/73

**Comment by marteinn** [comment]
Excellent, thanks @aait!
