### ISSUE TITLE
Last callback changes the Order status back to "On hold"

### ISSUE THREAD

**Issue by noaholsson** [SwedbankPay/swedbank-pay-woocommerce-payments#74]
We are experiencing a problem with the callback handling. It seems like they are not handled in the correct order. The order first changes the status to `Processing` and indicates that the payment is completed, right after that it gets changed back to `On hold` even though the payment is fully completed. 

<img width="284" alt="Screenshot 2021-02-01 at 14 22 38" src="https://user-images.githubusercontent.com/12989778/106762765-714beb00-6636-11eb-8d4d-f588fa4b1ce8.png">

Could you guys look into that asap? This is causing us a lot of extra work since we can't trust the status in Woocomece and have to check against Swedbank Pay.

Best Regards,
Noah

**Comment by aait** [comment]
Hi @noaholsson , we would require access to your site to investigate this issue. Please send an email to info@aait.se with insructions how to reach your site backend  + file-access.
