### ISSUE TITLE
First payment attempt fails, but the second payment attempt is successful

### ISSUE THREAD

**Issue by christianz123** [SwedbankPay/swedbank-pay-woocommerce-payments#77]
Hi
We have noticed that if the first payment attempt fails and the customer is doing a second successful attempt, then it will trigger some issues.

1. Customer attempts to pay by using e.g. Swish -> Fails for any kind of reason
2. Customer tries again with e.g. Credit -> Success
3. Order Confirmed
In the Payex admin portal we clearly see that the first attempt failed but the second attempt succeeded.
Everything is good so far, but we have seen that it will trigger some error scenarios.

First scenario: If the customer would like to do a refund, then we get an error message "Refund is unavailable".
Second scenario: The first payment attempt can sometimes trigger a  late update of the order in WooCommerce and change the status to "Failed" even though the second attempt was OK. 

This is causing some issues for us, any update is appreciated.

Thanks

**Comment by aait** [comment]
@christianz123 Do you mean `swedbank-pay-woocommerce-payments` plugin or `swedbank-pay-woocommerce-checkout` ?
Actually, little bit unclear for me. Could you make screencast please?

**Comment by christianz123** [comment]
Hi
I have attached a screenshot of the plugin page.
Please let me know if you need anything else?

Christian

From: aait ***@***.***>
Date: Monday, 17 May 2021 at 13:51
To: SwedbankPay/swedbank-pay-woocommerce-payments ***@***.***>
Cc: Christian Johansson ***@***.***>, Mention ***@***.***>
Subject: Re: [SwedbankPay/swedbank-pay-woocommerce-payments] First payment attempt fails, but the second payment attempt is successful (#77)

@christianz123<https://github.com/christianz123> Do you mean swedbank-pay-woocommerce-payments plugin or swedbank-pay-woocommerce-checkout ?
Actually, little bit unclear for me. Could you make screencast please?

**Comment by aait** [comment]
@christianz123 Sorry, could you ansewer my questions please?

**Comment by aait** [comment]
@christianz123 Please make a video how to reproduce these bugs

**Comment by christianz123** [comment]
Hi
I have tried a few times to reproduce the error but I haven't manage to trigger to error again.
So something have probably changed on my end or your end.
Close this issue for now.

Thanks

**Comment by christianz123** [comment]
Ok to close.
