### ISSUE TITLE
Hook not triggering

### ISSUE THREAD

**Issue by klingberg** [SwedbankPay/swedbank-pay-woocommerce-payments#82]
Hi!

I am trying to alter the new order recipient email on checkout. I am doing this via this hook "woocommerce_email_recipient_new_order" and it works fine for cash on delivery orders but this hook is not triggered when using Swish or Credit card payments.

Do you have any ideas why it is not triggered or do you have any recommendations for a workaround?

Best regards!

**Comment by aait** [comment]
@klingberg We've checked this and this hook was worked on our test environment.
You can check triggers which this hook being triggired:
https://github.com/woocommerce/woocommerce/blob/trunk/includes/emails/class-wc-email-new-order.php#L41
```php
			// Triggers for this email.
			add_action( 'woocommerce_order_status_pending_to_processing_notification', array( $this, 'trigger' ), 10, 2 );
			add_action( 'woocommerce_order_status_pending_to_completed_notification', array( $this, 'trigger' ), 10, 2 );
			add_action( 'woocommerce_order_status_pending_to_on-hold_notification', array( $this, 'trigger' ), 10, 2 );
			add_action( 'woocommerce_order_status_failed_to_processing_notification', array( $this, 'trigger' ), 10, 2 );
			add_action( 'woocommerce_order_status_failed_to_completed_notification', array( $this, 'trigger' ), 10, 2 );
			add_action( 'woocommerce_order_status_failed_to_on-hold_notification', array( $this, 'trigger' ), 10, 2 );
			add_action( 'woocommerce_order_status_cancelled_to_processing_notification', array( $this, 'trigger' ), 10, 2 );
			add_action( 'woocommerce_order_status_cancelled_to_completed_notification', array( $this, 'trigger' ), 10, 2 );
			add_action( 'woocommerce_order_status_cancelled_to_on-hold_notification', array( $this, 'trigger' ), 10, 2 );
```
Please make sure that you don't have conflict with 3party plugins.
if the problem is still here then contact us info@aait.se

**Comment by klingberg** [comment]
Thank you and sorry for the late reply. I will make some further tests and get back to you if the problem persists.

**Comment by aait** [comment]
@marteinn What do you mean?
