### ISSUE TITLE
"No successful authorization" - Wrong status in Woocommerce

### ISSUE THREAD

**Issue by christianz123** [SwedbankPay/swedbank-pay-woocommerce-payments#83]
Hi
When an order is not authorized by Swedbank/Payex, the status is not updated in WooCommerce.

1. Customer is doing an order
2. The Invoice payment is not authorized
3. The status is updated in Payex, see attached screenshot.
![Screenshot 2021-03-28 at 08 30 14](https://user-images.githubusercontent.com/67435890/112744389-fcdf5980-8f9f-11eb-85b1-6a1b74ecc434.png)
4. The status in WooCommerce is not updated. It is still "Inväntar betalning". No information about the failed payment. Exoected behaviour would be that the status is changed to "Misslyckad" and a note is attached to the order.

Thanks

**Comment by aait** [comment]
If thee is an error sent back to the shop we will display it. Otherwise refer to https://github.com/SwedbankPay/swedbank-pay-woocommerce-payments/issues/83
