### ISSUE TITLE
Order status is not updated if customer is not finalizing the payment

### ISSUE THREAD

**Issue by christianz123** [SwedbankPay/swedbank-pay-woocommerce-payments#84]
Hi
Sometimes the customer is not completing the payment e.g. not confirming the Swish payment with the smart phone.

1. Customer is doing an order
2. Customer check out the cart and selects a payment option e.g. Swish
3. Customer is not confirming the order with the BankID
4. The order status in Woocommerce is stuck in "Inväntar betalning". No information in the order about the payment.
5. Expected behavior would be that order status is changed to "Avbruten" after a timeout and a note is attached to the order.

Thanks

**Comment by aait** [comment]
1. Please navigate to WooCommerce -> Settings -> Products -> Inventory
2. Set Hold stock (minutes) to desired value 
https://i.imgur.com/cHmrsa6.png
