### ISSUE TITLE
Subscriptions auto renewal

### ISSUE THREAD

**Issue by christianz123** [SwedbankPay/swedbank-pay-woocommerce-payments#87]
Hi
I am trying to setup the subscriptions functionality in Woocommerce
https://woocommerce.com/products/woocommerce-subscriptions/

The Swedbank Pay Checkout indicates that it shall support auto renewals. See attached screenshot.

![Screenshot 2021-05-03 at 09 00 52](https://user-images.githubusercontent.com/67435890/116849080-4437b600-abee-11eb-80db-2f90cf4e4a1c.png)

During the checkout process everything seems fine. Only one payment option is available (credit card). I assume that is because of the auto renewal functionality. That is OK.

The problem occurs during the first renewal. A new renewal order is created by the system but the payment status is pending. The customer need to manually do a new payment from the account page. During that payment process all payments options are available.

Expected behaviour is that the customer shall not manually do a new payment. This should be automatic.

Thanks

**Comment by aait** [comment]
Hello. is the product a virtual product?

**Comment by christianz123** [comment]
No, it is of type "simple subscription. See attached screenshot.
![Screenshot 2021-05-03 at 14 02 19](https://user-images.githubusercontent.com/67435890/116873589-3c8d0700-ac18-11eb-97d8-40a9714591bb.png)

**Comment by aait** [comment]
@aait Can you attach screenshot of order view screen in the admin backend please?

**Comment by aait** [comment]
@aait btw, If we are talking about "Checkout" plugin then please open issue there https://github.com/SwedbankPay/swedbank-pay-woocommerce-checkout

**Comment by christianz123** [comment]
![Screenshot 2021-05-03 at 22 07 39](https://user-images.githubusercontent.com/67435890/116927620-2f920700-ac5c-11eb-9743-5d6f58ed6f0d.png)

**Comment by christianz123** [comment]
Any special info from the order page?

**Comment by christianz123** [comment]
HI again, any progress or findings on this topic? I have customers asking for this feature and need to find a way forward. Thanks.

**Comment by aait** [comment]
@christianz123 Hello! I need to clarify some information. Could you contact me please oleg@iskusnyh.pro?

**Comment by christianz123** [comment]
Sorry this issue is related to the checkout plugin. The naming is very similar :)
I created a new issue in the other repository. This one can be closed.

**Comment by aait** [comment]
https://github.com/SwedbankPay/swedbank-pay-woocommerce-checkout/issues/82
