### ISSUE TITLE
Instant capture of fee not working

### ISSUE THREAD

**Issue by marteinn** [SwedbankPay/swedbank-pay-woocommerce-payments#89]
Currently when placing an instant capture that contains a `WC_Order_Item_Fee` the fee are treated as a remaining capture amount. 

I propose a solution for this by either:
- `fee` is treated the same way as the regular order item in order
- Some kind on setting where we can instruct the plugin to treat fees to be instant captured
- A conditional auto capture (this is probably the cleanest solution)

**Comment by aait** [comment]
@marteinn Which settings you have?
It should be like that
![77Screenshot](https://user-images.githubusercontent.com/6286270/119133447-b5d08a80-ba5d-11eb-85aa-0784956c77ca.png)

**Comment by marteinn** [comment]
@aait Ah, thats it. I missed that "Fees" was an option. After activating "Fees" everything worked as expected. Thanks!

(Closing issue)
